# Generated by Django 5.2.7 on 2025-10-29 16:22

from django.db import migrations


def create_roles_and_users(apps, schema_editor):
    from django.contrib.auth.models import Group, Permission, User
    from django.contrib.contenttypes.models import ContentType

    # Crear roles
    roles = ['Admin', 'Medico', 'Paciente']
    grupos = {}
    for role in roles:
        grupo, created = Group.objects.get_or_create(name=role)
        grupos[role] = grupo

    # --- Asignación de permisos ---

    # Admin: todos los permisos
    grupos['Admin'].permissions.set(Permission.objects.all())

    # Medico: puede ver y cambiar citas, y ver pacientes
    grupos['Medico'].permissions.set(Permission.objects.filter(codename__in=[
        'view_cita', 'change_cita', 'view_paciente', 'view_medico'
    ]))

    # Paciente: puede agregar, ver y cambiar sus citas
    grupos['Paciente'].permissions.set(Permission.objects.filter(codename__in=[
        'view_cita'
    ]))

    # --- Crear usuarios por defecto ---

    admin, _ = User.objects.get_or_create(username='admin')
    admin.set_password('admin123')
    admin.is_superuser = True
    admin.is_staff = True
    admin.save()
    admin.groups.add(grupos['Admin'])

    medico, _ = User.objects.get_or_create(username='medico')
    medico.set_password('medico123')
    medico.is_staff = True
    medico.save()
    medico.groups.add(grupos['Medico'])

    paciente, _ = User.objects.get_or_create(username='paciente')
    paciente.set_password('paciente123')
    paciente.is_staff = False
    paciente.save()
    paciente.groups.add(grupos['Paciente'])


def delete_roles_and_users(apps, schema_editor):
    from django.contrib.auth.models import Group, User
    roles = ['Admin', 'Medico', 'Paciente']
    Group.objects.filter(name__in=roles).delete()
    User.objects.filter(username__in=['admin', 'medico', 'paciente']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_roles_and_users, delete_roles_and_users),
    ]
