# Generated by Django 5.2.7 on 2025-10-29 16:22

from django.db import migrations


def create_roles_and_users(apps, schema_editor):
    from django.contrib.auth.models import Group, Permission, User
    from django.contrib.contenttypes.models import ContentType

    # Create roles
    roles = ['Admin', 'Medico', 'Recepcionista']
    grupos = {}
    for role in roles:
        grupo, created = Group.objects.get_or_create(name=role)
        grupos[role] = grupo

    grupos['Admin'].permissions.set(Permission.objects.all())
    grupos['Medico'].permissions.set(Permission.objects.filter(codename__in=[
        'cita-list',
        'cita-update',
    ]))
    grupos['Recepcionista'].permissions.set(Permission.objects.filter(codename__in=[
        'cita-create',
        'cita-list',
    ]))

    admin, _ = User.objects.get_or_create(username='admin')
    admin.set_password('admin123')
    admin.is_superuser = True
    admin.is_staff = True
    admin.save()
    admin.groups.add(grupos['Admin'])

    medico, _ = User.objects.get_or_create(username='medico')
    medico.set_password('medico123')
    medico.is_staff = True
    medico.save()
    medico.groups.add(grupos['Medico'])

    recepcionista, _ = User.objects.get_or_create(username='recepcionista')
    recepcionista.set_password('recepcionista123')
    recepcionista.is_staff = True
    recepcionista.save()
    recepcionista.groups.add(grupos['Recepcionista'])

def delete_roles_and_users(apps, schema_editor):
    from django.contrib.auth.models import Group, User
    roles = ['Admin', 'Medico', 'Recepcionista']
    Group.objects.filter(name__in=roles).delete()
    User.objects.filter(username__in=['admin', 'medico', 'recepcionista']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_roles_and_users, delete_roles_and_users),
    ]
