# Generated by Django 5.2.7 on 2025-10-14 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Usuario",
        ),
    ]
