# Generated by Django 5.2.7 on 2025-10-21 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0002_delete_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medico",
            name="usuario",
        ),
    ]
