# Generated by Django 5.2.7 on 2025-10-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0004_alter_cita_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cita",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Pendiente", "Pendiente"),
                    ("Atendida", "Atendida"),
                    ("Cancelada", "Cancelada"),
                ],
                default="Pendiente",
                max_length=20,
            ),
        ),
    ]
